version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: reelverse
      POSTGRES_PASSWORD: reelverse
      POSTGRES_DB: reelverse_test
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reelverse -d reelverse_test"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "63790:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_test:
