/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISplitterPolicy,
  ISplitterPolicyInterface,
} from "../../../contracts/splitter/ISplitterPolicy";

const _abi = [
  {
    inputs: [],
    name: "usdc",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISplitterPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): ISplitterPolicyInterface {
    return new Interface(_abi) as ISplitterPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISplitterPolicy {
    return new Contract(address, _abi, runner) as unknown as ISplitterPolicy;
  }
}
