import * as dotenv from 'dotenv';
import { logger } from '../utils/logger';

dotenv.config();

interface EnvConfig {
  NODE_ENV: string;
  PORT: number;
  DATABASE_URL: string;
  REDIS_URL: string;
  JWT_SECRET: string;
  CORS_ORIGIN: string;
  SMART_ACCOUNT_MASTER_KEY: string;
  PAYMASTER_HMAC_SECRET: string;
  CONTENT_REGISTRY_ADDRESS: string;
  LIVEPEER_API_KEY: string;
  LIVEPEER_BASE_URL: string;
  CLOUDFLARE_R2_BUCKET_NAME: string;
  CONTENT_ENCRYPTION_KEY: string;
  PLATFORM_PRIVATE_KEY: string;
  LIVEPEER_WEBHOOK_SECRET: string;
  API_BASE_URL: string;
  LIVEPEER_WEBHOOK_ID: string;
  CCBILL_CLIENT_ACCOUNT: string;
  CCBILL_CLIENT_SUBACCOUNT: string;
  CCBILL_FORM_NAME: string;
  CCBILL_SALT: string;
  CCBILL_WEBHOOK_SECRET: string;
  SEGPAY_PACKAGE_ID: string;
  SEGPAY_MERCHANT_ID: string;
  SEGPAY_API_KEY: string;
  SEGPAY_WEBHOOK_SECRET: string;
  FRONTEND_URL: string;
  HLS_SIGNING_KEY: string;
  HLS_BASE_URL: string;
  MAX_CONCURRENT_SESSIONS: number;
  WEAVIATE_URL: string;
  MEILISEARCH_URL: string;
  MEILISEARCH_MASTER_KEY: string;
  OPENAI_API_KEY: string;
  HUGGINGFACE_API_KEY: string;
  AUTH_PROVIDER: 'dev' | 'privy';
  PRIVY_APP_ID?: string;
  PRIVY_APP_SECRET?: string;
  BICONOMY_API_KEY?: string;
  BICONOMY_BUNDLER_URL?: string;
  BICONOMY_PAYMASTER_URL?: string;
  BICONOMY_DAPP_ID?: string;
  ALCHEMY_API_KEY?: string;
  ALCHEMY_POLICY_ID?: string;
  ALCHEMY_RPC_URL?: string;
  RELAYER_ENABLED: boolean;
  RELAYER_POLL_MS: number;
  RELAYER_SIGNER_MODE?: 'file' | 'kms';
  USDC_CONTRACT_ADDRESS: string;
  REVENUE_SPLITTER_ADDRESS: string;
  NFT_ACCESS_ADDRESS: string;
  PLATFORM_WALLET_ADDRESS: string;
  PAYMASTER_ADDRESS: string;
  PAYMASTER_PRIVATE_KEY: string;
  ENTRY_POINT_ADDRESS: string;
  MAX_GAS_PER_USER_OP: string;
  DAILY_SPENDING_LIMIT: string;
  MONTHLY_SPENDING_LIMIT: string;
  POLYGON_RPC_URL: string;
  MUMBAI_RPC_URL: string;
  POLYGONSCAN_API_KEY?: string;
  GEMINI_API_KEY?: string;
  CHAIN_ID: number;
  SIMPLE_ACCOUNT_FACTORY_ADDRESS: string;
  SESSION_KEY_MANAGER_ADDRESS: string;
  DEV_OWNER_PRIVATE_KEY?: string;
  BUNDLER_URL?: string;
  CREDITS_DEFAULT_CURRENCY?: string;
  RATE_LIMIT_PREFIX: string;
  RATE_LIMIT_SPONSOR: string;
  RATE_LIMIT_SUBMIT: string;
  RATE_LIMIT_UPLOAD_START: string;
  RATE_LIMIT_AA_SESSION: string;
  RATE_LIMIT_BILLING: string;
  CONTENT_ACCESS_GATE_ADDRESS: string;
  UPLOAD_MANAGER_ADDRESS: string;
  SESSION_KEY_POLICY_JSON?: string;
  WALLETLESS_PROVIDER?: 'biconomy' | 'alchemy'; // Add WALLETLESS_PROVIDER
}

const getEnv = (): EnvConfig => {
  const env = process.env;

  const requiredEnv: (keyof EnvConfig)[] = [
    'NODE_ENV', 'PORT', 'DATABASE_URL', 'REDIS_URL', 'JWT_SECRET', 'CORS_ORIGIN',
    'SMART_ACCOUNT_MASTER_KEY', 'PAYMASTER_HMAC_SECRET',
    'CONTENT_REGISTRY_ADDRESS', 'LIVEPEER_API_KEY', 'LIVEPEER_BASE_URL',
    'CLOUDFLARE_R2_BUCKET_NAME', 'CONTENT_ENCRYPTION_KEY', 'PLATFORM_PRIVATE_KEY',
    'LIVEPEER_WEBHOOK_SECRET', 'API_BASE_URL', 'LIVEPEER_WEBHOOK_ID',
    'CCBILL_CLIENT_ACCOUNT', 'CCBILL_CLIENT_SUBACCOUNT', 'CCBILL_FORM_NAME',
    'CCBILL_SALT', 'CCBILL_WEBHOOK_SECRET', 'SEGPAY_PACKAGE_ID',
    'SEGPAY_MERCHANT_ID', 'SEGPAY_API_KEY', 'SEGPAY_WEBHOOK_SECRET',
    'FRONTEND_URL', 'HLS_SIGNING_KEY', 'HLS_BASE_URL', 'MAX_CONCURRENT_SESSIONS',
    'WEAVIATE_URL', 'MEILISEARCH_URL', 'MEILISEARCH_MASTER_KEY',
    'OPENAI_API_KEY', 'HUGGINGFACE_API_KEY', 'AUTH_PROVIDER',
    'USDC_CONTRACT_ADDRESS', 'REVENUE_SPLITTER_ADDRESS', 'NFT_ACCESS_ADDRESS',
    'PLATFORM_WALLET_ADDRESS', 'PAYMASTER_ADDRESS', 'PAYMASTER_PRIVATE_KEY',
    'ENTRY_POINT_ADDRESS', 'MAX_GAS_PER_USER_OP', 'DAILY_SPENDING_LIMIT',
    'MONTHLY_SPENDING_LIMIT', 'POLYGON_RPC_URL', 'MUMBAI_RPC_URL',
    'RELAYER_ENABLED', 'RELAYER_POLL_MS', 'CHAIN_ID', 'SIMPLE_ACCOUNT_FACTORY_ADDRESS',
    'SESSION_KEY_MANAGER_ADDRESS',
    'RATE_LIMIT_PREFIX', 'RATE_LIMIT_SPONSOR', 'RATE_LIMIT_SUBMIT',
    'RATE_LIMIT_UPLOAD_START', 'RATE_LIMIT_AA_SESSION', 'RATE_LIMIT_BILLING',
    'CONTENT_ACCESS_GATE_ADDRESS', 'UPLOAD_MANAGER_ADDRESS'
  ];

  // Add WALLETLESS_PROVIDER to requiredEnv if needed, or handle as optional
  // For now, it's optional as per the task description

  for (const key of requiredEnv) {
    if (!env[key]) {
      logger.error(`Missing required environment variable: ${key}`);
      // In a real app, you might throw an error or exit here
      // For now, we'll just log and proceed with undefined/defaults
    }
  }

  // Conditionally check DEV_OWNER_PRIVATE_KEY if AUTH_PROVIDER is 'dev'
  if (env.AUTH_PROVIDER === 'dev' && !env.DEV_OWNER_PRIVATE_KEY) {
    logger.warn('DEV_OWNER_PRIVATE_KEY is recommended for E2E/dev when AUTH_PROVIDER is set to \'dev\'.');
  }
  
  if (env.AUTH_PROVIDER === 'privy') {
    if (!env.PRIVY_APP_ID) {
      logger.error('Missing required environment variable: PRIVY_APP_ID when AUTH_PROVIDER is privy');
    }
    if (!env.PRIVY_APP_SECRET) {
      logger.error('Missing required environment variable: PRIVY_APP_SECRET when AUTH_PROVIDER is privy');
    }
  }

  if (!env.BUNDLER_URL) {
    logger.error('Missing required environment variable: BUNDLER_URL');
  }

  return {
    NODE_ENV: env.NODE_ENV || 'development',
    PORT: parseInt(env.PORT || '3001'),
    DATABASE_URL: env.DATABASE_URL || 'postgresql://reelverse:reelverse_password@localhost:5432/reelverse_db',
    REDIS_URL: env.REDIS_URL || 'redis://localhost:6379',
    JWT_SECRET: env.JWT_SECRET || 'super-secret-jwt-key',
    CORS_ORIGIN: env.CORS_ORIGIN || 'http://localhost:5173',
    SMART_ACCOUNT_MASTER_KEY: env.SMART_ACCOUNT_MASTER_KEY || 'a'.repeat(64), // Placeholder
    PAYMASTER_HMAC_SECRET: env.PAYMASTER_HMAC_SECRET || 'b'.repeat(64), // Placeholder
    CONTENT_REGISTRY_ADDRESS: env.CONTENT_REGISTRY_ADDRESS || '0x0000000000000000000000000000000000000002',
    LIVEPEER_API_KEY: env.LIVEPEER_API_KEY || 'dummy-livepeer-key',
    LIVEPEER_BASE_URL: env.LIVEPEER_BASE_URL || 'https://livepeer.studio/api',
    CLOUDFLARE_R2_BUCKET_NAME: env.CLOUDFLARE_R2_BUCKET_NAME || 'dummy-r2-bucket',
    CONTENT_ENCRYPTION_KEY: env.CONTENT_ENCRYPTION_KEY || 'c'.repeat(32), // 32-byte key
    PLATFORM_PRIVATE_KEY: env.PLATFORM_PRIVATE_KEY || 'd'.repeat(64), // 32-byte hex key
    LIVEPEER_WEBHOOK_SECRET: env.LIVEPEER_WEBHOOK_SECRET || 'e'.repeat(64),
    API_BASE_URL: env.API_BASE_URL || 'http://localhost:3001',
    LIVEPEER_WEBHOOK_ID: env.LIVEPEER_WEBHOOK_ID || 'dummy-webhook-id',
    CCBILL_CLIENT_ACCOUNT: env.CCBILL_CLIENT_ACCOUNT || '123456',
    CCBILL_CLIENT_SUBACCOUNT: env.CCBILL_CLIENT_SUBACCOUNT || '0000',
    CCBILL_FORM_NAME: env.CCBILL_FORM_NAME || 'cc_form',
    CCBILL_SALT: env.CCBILL_SALT || 'dummy-salt',
    CCBILL_WEBHOOK_SECRET: env.CCBILL_WEBHOOK_SECRET || 'f'.repeat(64),
    SEGPAY_PACKAGE_ID: env.SEGPAY_PACKAGE_ID || 'dummy-package',
    SEGPAY_MERCHANT_ID: env.SEGPAY_MERCHANT_ID || 'dummy-merchant',
    SEGPAY_API_KEY: env.SEGPAY_API_KEY || 'dummy-segpay-key',
    SEGPAY_WEBHOOK_SECRET: env.SEGPAY_WEBHOOK_SECRET || 'g'.repeat(64),
    FRONTEND_URL: env.FRONTEND_URL || 'http://localhost:5173',
    HLS_SIGNING_KEY: env.HLS_SIGNING_KEY || 'h'.repeat(64),
    HLS_BASE_URL: env.HLS_BASE_URL || 'https://hls.reelverse.com',
    MAX_CONCURRENT_SESSIONS: parseInt(env.MAX_CONCURRENT_SESSIONS || '5'),
    WEAVIATE_URL: env.WEAVIATE_URL || 'http://localhost:8080',
    MEILISEARCH_URL: env.MEILISEARCH_URL || 'http://localhost:7700',
    MEILISEARCH_MASTER_KEY: env.MEILISEARCH_MASTER_KEY || 'development-master-key-change-in-production',
    OPENAI_API_KEY: env.OPENAI_API_KEY || 'dummy-openai-key',
    HUGGINGFACE_API_KEY: env.HUGGINGFACE_API_KEY || 'dummy-huggingface-key',
    AUTH_PROVIDER: (env.AUTH_PROVIDER as 'dev' | 'privy') || 'dev',
    PRIVY_APP_ID: env.PRIVY_APP_ID,
    PRIVY_APP_SECRET: env.PRIVY_APP_SECRET,
    BICONOMY_BUNDLER_URL: env.BICONOMY_BUNDLER_URL,
    BICONOMY_PAYMASTER_URL: env.BICONOMY_PAYMASTER_URL,
    BICONOMY_DAPP_ID: env.BICONOMY_DAPP_ID,
    ALCHEMY_API_KEY: env.ALCHEMY_API_KEY,
    ALCHEMY_POLICY_ID: env.ALCHEMY_POLICY_ID,
    ALCHEMY_RPC_URL: env.ALCHEMY_RPC_URL,
    RELAYER_ENABLED: env.RELAYER_ENABLED === 'true',
    RELAYER_POLL_MS: parseInt(env.RELAYER_POLL_MS || '5000'),
    RELAYER_SIGNER_MODE: (env.RELAYER_SIGNER_MODE as 'file' | 'kms') || undefined,
    USDC_CONTRACT_ADDRESS: env.USDC_CONTRACT_ADDRESS || '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
    REVENUE_SPLITTER_ADDRESS: env.REVENUE_SPLITTER_ADDRESS || '0x0000000000000000000000000000000000000003',
    NFT_ACCESS_ADDRESS: env.NFT_ACCESS_ADDRESS || '0x0000000000000000000000000000000000000004',
    PLATFORM_WALLET_ADDRESS: env.PLATFORM_WALLET_ADDRESS || '0x0000000000000000000000000000000000000005',
    PAYMASTER_ADDRESS: env.PAYMASTER_ADDRESS || '0x0000000000000000000000000000000000000006',
    PAYMASTER_PRIVATE_KEY: env.PAYMASTER_PRIVATE_KEY || 'i'.repeat(64),
    ENTRY_POINT_ADDRESS: env.ENTRY_POINT_ADDRESS || '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789',
    MAX_GAS_PER_USER_OP: env.MAX_GAS_PER_USER_OP || '10000000000000000', // 0.01 ETH
    DAILY_SPENDING_LIMIT: env.DAILY_SPENDING_LIMIT || '1000000000000000000', // 1 ETH
    MONTHLY_SPENDING_LIMIT: env.MONTHLY_SPENDING_LIMIT || '10000000000000000000', // 10 ETH
    POLYGON_RPC_URL: env.POLYGON_RPC_URL || 'https://polygon-rpc.com',
    MUMBAI_RPC_URL: env.MUMBAI_RPC_URL || 'https://rpc-mumbai.maticvigil.com',
    POLYGONSCAN_API_KEY: env.POLYGONSCAN_API_KEY,
    GEMINI_API_KEY: env.GEMINI_API_KEY,
    CHAIN_ID: parseInt(env.CHAIN_ID || '11155111'), // Default to Sepolia
    SIMPLE_ACCOUNT_FACTORY_ADDRESS: env.SIMPLE_ACCOUNT_FACTORY_ADDRESS || '0x9406Cc6185a346906296840746129e125aF35fEd', // Default SimpleAccountFactory address for Sepolia
    SESSION_KEY_MANAGER_ADDRESS: env.SESSION_KEY_MANAGER_ADDRESS || '0x0000000000000000000000000000000000000007',
    DEV_OWNER_PRIVATE_KEY: env.AUTH_PROVIDER === 'dev' ? env.DEV_OWNER_PRIVATE_KEY : undefined,
    BUNDLER_URL: env.BUNDLER_URL,
    CREDITS_DEFAULT_CURRENCY: env.CREDITS_DEFAULT_CURRENCY || 'USDC',
    RATE_LIMIT_PREFIX: env.RATE_LIMIT_PREFIX || 'rl:',
    RATE_LIMIT_SPONSOR: env.RATE_LIMIT_SPONSOR || '20/min',
    RATE_LIMIT_SUBMIT: env.RATE_LIMIT_SUBMIT || '30/min',
    RATE_LIMIT_UPLOAD_START: env.RATE_LIMIT_UPLOAD_START || '5/min',
    RATE_LIMIT_AA_SESSION: env.RATE_LIMIT_AA_SESSION || '10/hour',
    RATE_LIMIT_BILLING: env.RATE_LIMIT_BILLING || '20/min',
    CONTENT_ACCESS_GATE_ADDRESS: env.CONTENT_ACCESS_GATE_ADDRESS || '0x0000000000000000000000000000000000000008', // Placeholder
    UPLOAD_MANAGER_ADDRESS: env.UPLOAD_MANAGER_ADDRESS || '0x0000000000000000000000000000000000000009', // Placeholder
    SESSION_KEY_POLICY_JSON: env.SESSION_KEY_POLICY_JSON,
    WALLETLESS_PROVIDER: (env.WALLETLESS_PROVIDER as 'biconomy' | 'alchemy') || undefined, // Retrieve WALLETLESS_PROVIDER
  };
};

export const env = getEnv();