/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
import type * as registry from "./registry";
export type { registry };
import type * as splitter from "./splitter";
export type { splitter };
